// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGamePlayTags.h"

namespace MMGameplayTags
{
	MINIMAP_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	MINIMAP_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Mouse);
	MINIMAP_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Crouch);
	MINIMAP_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);
	MINIMAP_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Attack);
	MINIMAP_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Block);
	MINIMAP_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_SwapWeapon);

	MINIMAP_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayAbility_Jump);
	MINIMAP_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayAbility_Attack);
	MINIMAP_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayAbility_Attack_Weapon);
	MINIMAP_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayAbility_Block);
	MINIMAP_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayAbility_Block_Weapon);
	MINIMAP_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayAbility_SwapEquipping);
	MINIMAP_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayAbility_SwapWeapon);
	MINIMAP_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayAbility_Behavior_SurvivesDeath);

	MINIMAP_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Death);
	MINIMAP_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Reset);
	MINIMAP_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_RequestReset);
	MINIMAP_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_SwapWeapon);
	MINIMAP_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_SwapEquipping);

	MINIMAP_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Damage);
	MINIMAP_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Heal);

	MINIMAP_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Crouching);
	MINIMAP_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death);
	MINIMAP_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death_Dying);
	MINIMAP_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death_Dead);
	MINIMAP_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Weapon_Equipped);
	MINIMAP_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Weapon_Equipping);
	MINIMAP_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Attacking);
	MINIMAP_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Blocking);

	MINIMAP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Gameplay_DamageImmunity);

	// These are mappings from MovementMode enums to GameplayTags associated with those enums (below)
	MINIMAP_API	extern const TMap<uint8, FGameplayTag> MovementModeTagMap;

	MINIMAP_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Walking);
	MINIMAP_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_NavWalking);
	MINIMAP_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Falling);
	MINIMAP_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Swimming);
	MINIMAP_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Flying);
};